StudyBuddy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name="study/index.html")),
    path('admin/', admin.site.urls),
    path('study/', include('study.urls')),
    path('accounts/', include('allauth.urls'))
]

study/urls.py
"""
URLs
"""

from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'study'

# URLs with "login_required" are behind Google Login
# URLs with <int:pk> refer to specific groups
urlpatterns = [
    path('profile', views.update_profile, name='profile'),
    path('search-groups', login_required(views.GroupSearchResultsView.as_view()), name='search-groups'),
    path('search-members', login_required(views.MemberSearchResultsView.as_view()), name='search-members'),
    path('groups/<int:pk>', login_required(views.GroupView.as_view()), name='group'),
    path('join-group/<int:pk>', login_required(views.join_group), name='join-group'),
    path('create-group', login_required(views.CreateGroup.as_view()), name='create-group'),
]

study/models.py
"""
Models
"""

from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from groupy.client import Client


# Custom model Profile is linked to a specific User for authentication
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    
    # Custom labels for form selection *CHANGE EACH YEAR*
    YEAR_CHOICES = [
        ('2021', '2021'),
        ('2022', '2022'),
        ('2023', '2023'),
        ('2024', '2024'),
    ]
    grad_year = models.CharField('Graduation Year',max_length=30, choices=YEAR_CHOICES, blank=True)
    major = models.CharField(max_length=50, blank=True)
    student_id = models.CharField('Student ID', max_length=10, blank=True)
    groups = models.ManyToManyField('StudyGroup')
    # Generate the tags and filtering options
    courses = TaggableManager("Courses", "ex: CS1110, ECON1010")  

    # Initial attempt to generate schedules *NOT IN USE*
    schedule = models.TextField(max_length=500, blank=True)        

    # Return the email as the string representation of Profile
    def __str__(self):
        return self.user.email

"""
REFERENCES
Title: Creating a User Profile page using OneToOne field with User Model
Author: Roma
Date: Oct 4, 2020
URL: https://stackoverflow.com/questions/45936087/creating-a-user-profile-page-using-onetoone-field-with-user-model
"""
# Ensures that whenever a User is created their Profile is also created
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


# Ensures that whenever a User is saved their Profile is also saved
@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


# Custom model StudyGroup has a many-to-many relationship with Users
class StudyGroup(models.Model):
    id = models.AutoField(primary_key=True)
    group_name = models.CharField(max_length=50, unique=True, blank=False)
    topic_course = models.CharField(max_length=20)
    members = models.ManyToManyField(User)
    tags = TaggableManager()
    
    """
    REFERENCES
    Title: Groupy
    Author: rhgrant10
    Date: Nov 9, 2020
    URL: https://github.com/rhgrant10/Groupy
    License: Apache 2.0 License
    """
    # Attributes needed for GroupMe integration
    groupme_option = models.BooleanField("Create GroupMe?", default=False, blank=False)     # Does the user want to generate a group message?
    groupme_id = models.CharField(max_length=100)                                           # Unique identifier provided by API
    groupme_url = models.CharField(max_length=100)                                          # Unique share URL provided by API

    class Meta:
        verbose_name = 'Study Group'

    def __str__(self):
        return self.group_name

    # Custom save method used to generate external GroupMe message based on form submission
    def save(self, *args, **kwargs):
        
        # Check to see if the group needs a GroupMe
        if self.groupme_option:
            
            # Create GroupMe
            token = "GSTVyt66iVgWWj45IVAlXv5LLegUcSuLSyRMfBgP"
            client = Client.from_token(token)
            groupme = client.groups.create(name=self.group_name, share=True)
            
            # Obtain identifier and share URL
            self.groupme_id = groupme.id
            self.groupme_url = groupme.share_url
            
            # Post a message in the GroupMe
            groupme.post("Welcome to GroupMe: " + self.group_name + "!")

        super(StudyGroup, self).save(*args, **kwargs)

study/forms.py
"""
Forms
"""

from django import forms
from django.contrib.auth.models import User
from .models import Profile, StudyGroup

from groupy.client import Client

"""
REFERENCES
Title: Django allauth saving custom user profile fields with signup form
Author: prithvi
Date: Oct 3, 2020
URL: https://stackoverflow.com/questions/44133562/django-add-placeholder-text-to-form-field
"""
# Initial signup form was designed to let users customize their names *NOT IN USE*
class SignupForm(forms.Form):
    first_name = forms.CharField(max_length=30, label='First Name')
    last_name = forms.CharField(max_length=30, label='Last Name')

    def signup(self, request, user):
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.save()


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name')

"""
REFERENCES
Title: Django add placeholdertext to form field
Author: aziminia
Date: Nov 16, 2020
URL: https://stackoverflow.com/questions/44133562/django-add-placeholder-text-to-form-field
"""
class ProfileForm(forms.ModelForm):
    # Including placeholder labels for profile form submission
    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        self.fields['bio'].widget.attrs['placeholder'] = 'Please include a brief description of yourself! Feel free to list any specific topics where you are looking for help or feel you could help others.'
        self.fields['courses'].widget.attrs['placeholder'] = 'Ex: CS1110, CS3240, ...'

    class Meta:
        model = Profile
        # Include all the relevant fields in the profile form
        fields = ('bio', 'grad_year', 'major', 'student_id', 'courses')


class CustomMMCF(forms.ModelMultipleChoiceField):
    # Custom labels for the Multiple Choice field selections
    def label_from_instance(self, User):
        return "%s" % User.email

"""
REFERENCES
Title: Django Forms for Many-to-Many Fields
Author: Alice Campkin
Date: Oct 26, 2020
URL: https://medium.com/swlh/django-forms-for-many-to-many-fields-d977dec4b024
"""
class GroupForm(forms.ModelForm):
    # Form that allows users to create a new group and select group members
    class Meta:
        model = StudyGroup
        fields = ("group_name", "topic_course", "members", "groupme_option")
    
    # Use the default form options
    group_name = forms.CharField(max_length=50)
    topic_course = forms.CharField(max_length=20)
    
    # Add a checkbox selection option to the form with CustomMMCF labels
    members = CustomMMCF(
        queryset=User.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )   

study/views.py
"""
Views
"""

from django.views.generic import TemplateView, ListView, CreateView, View, DetailView
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.contrib import  messages
from django.db import transaction
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from .forms import UserForm, ProfileForm, GroupForm
from .models import StudyGroup, Profile
from taggit.models import Tag


# Initial attempt at generating StudyBuddy homepage *NOT IN USE*
class IndexView(View):
    template_name = 'study/base.html'

# Generate the individual StudyGroup pages
class GroupView(DetailView):
    model = StudyGroup
    template_name = 'study/group.html'

    def get_queryset(self):
        return StudyGroup.objects.all()

# Initial attempt at generating GroupMe message *NOT IN USE*
class GroupMeView(DetailView):
    model = StudyGroup
    template_name = 'study/group_message.html'

    def get_queryset(self):
        return StudyGroup.objects.all()


"""
REFERENCES
Title: Creating a User Profile page using OneToOne field with User Model
Author: Roma
Date: Oct 4, 2020
URL: https://stackoverflow.com/questions/45936087/creating-a-user-profile-page-using-onetoone-field-with-user-model
"""
# Update Profile that is linked to a User update
@login_required
@transaction.atomic
def update_profile(request):
    
    # Check to make sure that a 'POST' submission was recieved
    if request.method == 'POST':

        # Obtain the user and profile form submissions
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, instance=request.user.profile)
        
        # Ensure that both the user and profile forms are valid
        if user_form.is_valid() and profile_form.is_valid():
            
            # Save both forms
            user_form.save()
            profile_form.save()

            # Create a user object from the form
            newuser = user_form.save(commit=False)
            newuser.user = request.user
            newuser.save()
            user_form.save_m2m()

            # Create a profile object from the form
            newprof = profile_form.save(commit=False)
            newprof.user = request.user
            newprof.save()
            profile_form.save_m2m()

            # Send a success message
            messages.success(request, ('Your profile was successfully updated!'))
            return redirect('study:profile')
        
        # Otherwise, generate an error message
        else:
            messages.error(request, ('Please correct the error below.'))
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)
    
    # Return to a view of the user and profile forms
    return render(request, 'study/profile.html', {
        'user_form': user_form,
        'profile_form': profile_form
    })


"""
REFERENCES
Title: Django Search Tutorial
Author: Will Vincent
Date: Oct 13, 2020
URL: https://learndjango.com/tutorials/django-search-tutorial
"""
# Return the StudyGroup search results for a specific search term 'q'
class GroupSearchResultsView(ListView):
    model = StudyGroup
    template_name = 'study/group_search_results.html'
    
    # Define the query that will be used with the search bar
    def get_queryset(self):
        query = self.request.GET.get('q')
        
        # If there is a search term, filter StudyGroups based on terms
        if query:
            object_list = StudyGroup.objects.filter(
                Q(group_name__icontains=query) | Q(topic_course__icontains=query)
            )

        # If there is no search term, return a list of all the StudyGroups
        else:
            object_list = StudyGroup.objects.all()
        return object_list.distinct().order_by('group_name')


"""
REFERENCES
Title: Django Search Tutorial
Author: Will Vincent
Date: Oct 13, 2020
URL: https://learndjango.com/tutorials/django-search-tutorial
"""
# Return the Profile search results for a specific search term 'q'
class MemberSearchResultsView(ListView):
    model = StudyGroup
    template_name = 'study/member_search_results.html'
    
    # Define the query that will be used with the search bar
    def get_queryset(self):
        query = self.request.GET.get('q')
        
        # If there is a search term, filter Profiles based on terms
        if query:
            object_list = Profile.objects.filter(
                Q(bio__icontains=query) | 
                Q(major__icontains=query) | 
                Q(student_id__icontains=query) | 
                # Querying for the couse tags (limited due to only matching on the while tag)
                Q(courses__name__in=[query]) |      
                # Querying for individual first and last name                                                                                                  
                Q(user__first_name__icontains=query) |
                Q(user__last_name__icontains=query) |
                # Querying for full name
                Q(user__first_name__icontains=query.split(' ')[0], user__last_name__icontains=query.split(' ')[-1])
            )

        # If there is no search term, return a list of all the StudyGroups
        else:
            object_list = Profile.objects.all()
        return object_list.distinct().order_by('user__last_name')

# Use the default model for for StudyGroup creation
class CreateGroup(CreateView):
    model = StudyGroup
    form_class = GroupForm
    template_name = 'study/create_group.html'
    success_url = 'search-groups'
    

# Join a StudyGroup via button and return the new list of members
def join_group(request, pk):

    # Obtain the current user
    new_member = request.user

    # Find the group that matches the URL request
    group = StudyGroup.objects.get(id=pk)

    # Add the new member and redirect to the group page
    group.members.add(new_member)
    group.save()

    # Redirect to the StudyGroup profile page
    return redirect('study:group', pk)

study/templates/study/base.html
{% load static %}
<!--
*  REFERENCES
*  Title: django-allauth
*  Sponsor: IntenCT
*  Date: Oct 4, 2020
*  URL: https://github.com/pennersr/django-allauth
*  Software License: MIT License

*  Title: Django Bootstrap Base Template
*  Author: Adi Ramadhan
*  Date: Sep 24, 2020
*  URL: https://adiramadhan17.medium.com/django-bootstrap-base-template-eadbd1ed76af

*  Title: Sticky footer with fixed navbar
*  Date: Nov 16, 2020
*  URL: https://getbootstrap.com/docs/4.1/examples/sticky-footer-navbar/
*  Software License: MIT License
-->
<!doctype html>
<html lang="en">
  <head>
    <!-- Set up CSS configuration for Bootstrap compatibility -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'study/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'study/sticky-footer.css' %}">
    <title>
        Project 1-06
    </title>
  
  </head>

  <!-- Navbar at the top of the page -->
  <nav class="navbar navbar-dark"  style="background-color: #FFA46C;">
    <a class="navbar-brand" href="/"><b style="letter-spacing: 2px;">StudyBuddy</b></a>
  </nav>

  <body>
    <main role="main" class="container">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-8">
          <h2 class="mt-5">
            {% block class_name %}
            StudyBuddy
            {% endblock %}
            </h2>
          <hr class="mt-0 mb-4">
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </div>
  </main>
  
  <!-- Footer at the top of the page -->
  <div class="mt-5">
    <footer class="footer">
      <div class="container">
        
        <!-- Copyright message and footer contents -->
        <span class="text-muted">© 2020 Copyright:
          <a href="https://github.com/uva-cs3240-f20/project-1-06">Team-1-06</a>
        </span>
      </div>
    </footer>
  </div>
</html>

study/templates/study/create_group.html
{% extends "study/base.html" %}

{% block class_name %}
Create a Group
{% endblock %}

{% block content %}
<div class="pb-3">

<!-- Generate the group create form -->
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <!-- Adding a save button -->
    <button class="btn btn-primary" type="submit">Save changes</button>
</form>
</div>
{% endblock %}

study/templates/study/created_group.html
{% extends "study/base.html" %}

{% block title %}Your Group{% endblock %}
{% block content %}
yay you created a group!

{% endblock %}

study/templates/study/group.html
{% extends "study/base.html" %}

{% block class_name %}
  {% csrf_token %}
  {{ studygroup.group_name }}
{% endblock %}

{% block content %}

<!-- Formatting for individual group pages -->
<div class="pb-4">
<h5>Topic</h5>
<div>{{studygroup.topic_course}}</div>
</div>
<div class="pb-4">
    <ul class="list-group"> 
    <h5>Members</h5>
      
    <!-- List all the members in the group -->
      {% for member in studygroup.members.all %}
        <li class="list-group-item">
        {{ member.get_full_name }}
        </li>
      {% endfor %}
    </ul>
    </div>
    
    <!-- Button for current non-member to join a Group -->
    {% if user in studygroup.members.all %}
    {% else %}
    <div class="pb-2">
      <a class="btn btn-primary btn-sm btn-block"  href="{% url 'study:join-group' studygroup.id %}"> Click here to join! </a>
    </div>
    {% endif %}
    
    <!-- Button to join a GroupMe -->
    {% if studygroup.groupme_option %}
    {% if user in studygroup.members.all %}
    <div class="pb-3">
        <a class="btn btn-link btn-sm btn-block" href="{{ studygroup.groupme_url }}" target="_blank">Connect with GroupMe</a>
    </div>

    <!-- Disable the link for users who are not a member of the StudyGroup -->
    {% else %}
    <div class="pb-3">
      <button type="button" class="btn btn-link btn-sm btn-block" disabled>Connect with GroupMe</button>
    </div>
    {% endif %}
    {% endif %}

    <!-- Button to return to Homepage -->
    <div class="pb-5 pt-5">
        <a class="btn btn-secondary" href="/" role="button">Back to Home</a>
    </div>
{% endblock %} 

study/templates/study/group_search_results.html
{% extends "study/base.html" %}

{% block class_name %}
Study Groups
{% endblock %}


{% block content %}
<div>
  <p>Search by Group Name or Topic</p>
</div>
<!-- Search bar -->
<div class="pb-4">
<form action="{% url 'study:search-groups' %}" method="get">
    <input name = "q" class="form-control" type="text" placeholder="Search" aria-label="Search">
</form>
</div>

<div class="pb-4">
<ul class="list-group"> 
  
  <!-- Message displayed when there are no available groups -->
  {% if not object_list %}
  No study groups are available at this time.
  {% endif %}

  <!-- Loop through all the groups in the query -->
  {% for group in object_list %}
    <li class = "list-group-item">
        
      <!-- Link to the specific group page -->
        <div><a href="{% url 'study:group' group.id %}">{{ group.group_name }}</a></div>
        <small>Topic: {{ group.topic_course }}</small>
    </li>
  {% endfor %}
</ul>
</div>

<!-- Additional navigation buttons -->
<div class = "pb-3">
<button type="button" class="btn btn-primary" onclick="window.location.href='/study/create-group';">Create Group</button> 
</div>
<div class = "pb-5">
  <a class="btn btn-secondary" href="/" role="button">Back to Home</a>
</div>
{% endblock %}

study/templates/study/index.html
{% extends "study/base.html" %}

{% block class_name %}

<!-- Load socialaccount for authentication checks -->
{% load socialaccount %}
<html>
  <body>
  
  <!-- Check to see if the user is authenticated before generating homepage -->
  {% if user.is_authenticated %}
  Homepage
  {% else %}
  <h1>StudyBuddy</h1>
  {% endif %}
  </body>
</html>
{% endblock %}

{% block content %}

<!-- Load socialaccount for authentication checks -->
{% load socialaccount %}
<html>
  <body>
  {% if user.is_authenticated %}
      
    <!-- If the user is authenticated, load their profile information -->
    <p>Welcome, {{ user.get_full_name }}!</p>
    <ul>
      <li class = "pb-3"><b>Email: </b>{{ user.email }}</li>
      <li class = "pb-3"><b>Bio: </b>{{ user.profile.bio }}</li>
      <li class = "pb-3"><b>Graduation Year: </b>{{ user.profile.grad_year }}</li>
      <li class = "pb-3"><b>Major: </b>{{ user.profile.major }}</li>
       <li class = "pb-3"><b>Computing ID: </b>{{ user.profile.student_id }}</li>
      <li class = "pb-3"><b>Courses: </b>
      <!-- List all the relevant tags for the user -->
      {% for tag in user.profile.courses.all %}
        <button type="button" class="mb-2 btn btn-outline-secondary btn-sm" onclick="window.location.href='/study/search-groups?q='+'{{tag.name}}';">{{ tag.name }}</button> 
      {% endfor %}
      </li>
    </ul>
    
    <!-- Navigation buttons for groups search and group creation -->
    <p>
    <button type="button" class="btn btn-primary" onclick="window.location.href='/study/search-members';">View Members</button> 
    <button type="button" class="btn btn-primary" onclick="window.location.href='/study/search-groups';">View Groups</button> 
    <button type="button" class="btn btn-link" onclick="window.location.href='/study/create-group';">Create Group</button> 
    </p>
  
    <!-- Navigation buttons for profile and logout -->
    <p>
    <button type="button" class="btn btn-secondary btn-sm" onclick="window.location.href='/study/profile';">Edit Profile</button>
    <button type="button" class="btn btn-secondary btn-sm" onclick="window.location.href='/accounts/logout/';">Logout</button>
    </p>
  
  {% else %}

  <!-- If the user is not authenticated, generate a login screen -->
  <a class="btn btn-secondary" href="{% provider_login_url 'google' %}" role="button">Login with Google</a>
  {% endif %}

  </body>
</html>
{% endblock %}

study/templates/study/join_group.html
{% extends "study/base.html" %}

{% block class_name %}
  {% csrf_token %}
  {{ studygroup.group_name }}
{% endblock %}

{% block content%}
    <header>Joined Group!</header>
    <div class= "pb-3">
        <a class="btn btn-success" href="{% url 'study:group' studygroup.id %}">Return to { studygroup.group_name }</a>
    </div>
{% end block %}

study/templates/study/member_search_results.html
{% extends "study/base.html" %}

{% block class_name %}
Members
{% endblock %}


{% block content %}
<div>
  <p>Search by Name, Student ID, Major, Courses, or Bio</p>
</div>
<!-- Search bar -->
<div class="pb-4">
<form action="{% url 'study:search-members' %}" method="get">
    <input name = "q" class="form-control" type="text" placeholder="Search" aria-label="Search">
</form>
</div>

<div class="pb-4">
<ul class="list-group"> 
  
  <!-- Message displayed when there are no available members -->
  {% if not object_list %}
  No members are available at this time.
  {% endif %}

  <!-- Loop through all the Profiles in the query -->
  {% for member in object_list %}
    <li class = "list-group-item">
        
      <!-- Member information -->
      <div><h6 class="mb-1">{{ member.user.get_full_name }}</h6></div>
      <div ><small><b>Email: </b>{{ member.user.email }}</small></div>
      <div><small><b>Student ID: </b>{{ member.student_id }}</small></div>
      <div><small><b>Graduation Year: </b>{{ member.grad_year }}</small></div>
      <div><small><b>Major: </b>{{ member.major }}</small></div>
      <div><small><b>Courses: </b>
        {%for course in member.courses.all%}
        {{ course.name }}
        {%endfor%}
        </small></div>
      <div><small><em>{{ member.bio }}</em></small></div>
    </li>
  {% endfor %}
</ul>
</div>

<!-- Additional navigation buttons -->
<div class = "pb-5">
  <a class="btn btn-secondary" href="/" role="button">Back to Home</a>
</div>
{% endblock %}

study/templates/study/profile.html
{% extends "study/base.html" %}
<!--
*  REFERENCES
*  Title: Django what is the best way to format forms?
*  Author: Games Brainiac
*  Date: Nov 16, 2020
*  URL: https://stackoverflow.com/questions/18742261/django-what-is-the-best-way-to-format-forms
-->

{% block class_name %}
Update Profile
{% endblock %}

{% block content %}
<div class="pb-3">

<!-- Custom form fields using fieldWrapper -->
<form method="post">
    {% csrf_token %}
    <div class="fieldWrapper">
        <div class = "pb-3">
            <label>First Name</label>
                <div>
                    {{ user_form.first_name }}
                </div>
        </div>
    </div>
    <div class="fieldWrapper">
        <div class = "pb-3">
            <label>Last Name</label>
                <div>
                    {{ user_form.last_name }}
                </div>
        </div>
    </div>
    <div class="fieldWrapper">
        <div class = "pb-3">
            <label>Bio</label>
                <div>
                    {{ profile_form.bio }}
                </div>
        </div>
    </div>
    <div class="fieldWrapper">
        <div class = "pb-3">
            <label>Graduation Year</label>
                <div>
                    {{ profile_form.grad_year }}
                </div>
        </div>
    </div>
    <div class="fieldWrapper">
        <div class = "pb-3">
            <label>Major</label>
                <div>
                    {{ profile_form.major }}
                </div>
        </div>
    </div>
    <div class="fieldWrapper">
        <div class = "pb-3">
            <label>Computing ID</label>
                <div>
                    {{ profile_form.student_id }}
                </div>
        </div>
    </div>
    <div class="fieldWrapper">
        <div class = "pb-3">
            <label>Course List</label>
                <div>
                    {{ profile_form.courses }}
                </div>
        </div>
    </div>
    <button class="btn btn-primary" type="submit">Save Changes</button>
</form>
</div>

<!-- Navigation buttons -->
<div class = "pb-5">
    <a class="btn btn-secondary" href="/" role="button">Back to Home</a>
</div>

{% endblock %}

study/templates/study/search_results.html
{% extends "study/base.html" %}

{% block class_name %}
Study Groups
{% endblock %}


{% block content %}

<!-- Search bar -->
<div class="pb-4">
<form action="{% url 'study:search' %}" method="get">
    <input name = "q" class="form-control" type="text" placeholder="Search" aria-label="Search">
</form>
</div>

<div class="pb-4">
<ul class="list-group"> 
  
  <!-- Message displayed when there are no available groups -->
  {% if not object_list %}
  No study groups are available at this time.
  {% endif %}

  <!-- Loop through all the groups in the query -->
  {% for group in object_list %}
    <li class = "list-group-item">
        
      <!-- Link to the specific group page -->
        <div><a href="{% url 'study:group' group.id %}">{{ group.group_name }}</a></div>
        <small>Topic: {{ group.topic_course }}</small>
    </li>
  {% endfor %}
</ul>
</div>

<!-- Additional navigation buttons -->
<div class = "pb-3">
<button type="button" class="btn btn-primary" onclick="window.location.href='/study/create-group';">Create Group</button> 
</div>
<div class = "pb-5">
  <a class="btn btn-secondary" href="/" role="button">Back to Home</a>
</div>
{% endblock %}